name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        if: ${{ job.status != 'failure' }}
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/apps/devmasters/frontend
            git pull
            sudo systemctl restart nginx

      - name: Stop Workflow on Error
        if: ${{ job.status == 'failure' }}
        run: exit 1
